services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile

    working_dir: /app

    volumes:
      # Projektdateien vom Host
      - .:/app

      # Composer-Abhängigkeiten bleiben im Container-Volume erhalten
      - vendor:/app/vendor

    tty: true
    stdin_open: true

    # Hält den Entwicklungscontainer aktiv
    command: tail -f /dev/null

volumes:
  vendor: